/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentCreateNestedManyWithoutArticlesInput } from "./CommentCreateNestedManyWithoutArticlesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { TagCreateNestedManyWithoutArticlesInput } from "./TagCreateNestedManyWithoutArticlesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ArticleCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutArticlesInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutArticlesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  published?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => TagCreateNestedManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => TagCreateNestedManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => TagCreateNestedManyWithoutArticlesInput, {
    nullable: true,
  })
  tags?: TagCreateNestedManyWithoutArticlesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tagsAssociation?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ArticleCreateInput as ArticleCreateInput };
