/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Article as PrismaArticle,
  Comment as PrismaComment,
  Tag as PrismaTag,
  User as PrismaUser,
} from "@prisma/client";

import { ArticleWhereInput } from "./ArticleWhereInput";
import { Article } from "./Article";
import { ArticleWhereUniqueInput } from "./ArticleWhereUniqueInput";

export class ArticleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ArticleCountArgs, "select">): Promise<number> {
    return this.prisma.article.count(args);
  }

  async articles<T extends Prisma.ArticleFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ArticleFindManyArgs>
  ): Promise<PrismaArticle[]> {
    return this.prisma.article.findMany<Prisma.ArticleFindManyArgs>(args);
  }
  async article<T extends Prisma.ArticleFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ArticleFindUniqueArgs>
  ): Promise<PrismaArticle | null> {
    return this.prisma.article.findUnique(args);
  }
  async createArticle<T extends Prisma.ArticleCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ArticleCreateArgs>
  ): Promise<PrismaArticle> {
    return this.prisma.article.create<T>(args);
  }
  async updateArticle<T extends Prisma.ArticleUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ArticleUpdateArgs>
  ): Promise<PrismaArticle> {
    return this.prisma.article.update<T>(args);
  }
  async deleteArticle<T extends Prisma.ArticleDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ArticleDeleteArgs>
  ): Promise<PrismaArticle> {
    return this.prisma.article.delete(args);
  }

  async findComments(
    parentId: string,
    args: Prisma.CommentFindManyArgs
  ): Promise<PrismaComment[]> {
    return this.prisma.article
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .comments(args);
  }

  async findTags(
    parentId: string,
    args: Prisma.TagFindManyArgs
  ): Promise<PrismaTag[]> {
    return this.prisma.article
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tags(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.article
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
  async FetchAllPublishedArticles(
    args: ArticleWhereInput[]
  ): Promise<Article[]> {
    throw new Error("Not implemented");
  }
  async FetchArticleById(args: ArticleWhereUniqueInput): Promise<Article> {
    throw new Error("Not implemented");
  }
}
